use serde::{Deserialize, Serialize};
use std::error::Error;
use strum::EnumIter;

#[derive(Debug, Hash, Eq, PartialEq, Deserialize, Serialize, Clone, EnumIter, PartialOrd, Ord)]
pub enum CountryCode {
    AFG,
    ALB,
    DZA,
    ASM,
    AND,
    AGO,
    AIA,
    ATA,
    ATG,
    ARG,
    ARM,
    ABW,
    AUS,
    AUT,
    AZE,
    BHS,
    BHR,
    BGD,
    BRB,
    BLR,
    BEL,
    BLZ,
    BEN,
    BMU,
    BTN,
    BOL,
    BIH,
    BWA,
    BRA,
    IOT,
    BRN,
    BGR,
    BFA,
    BDI,
    CPV,
    KHM,
    CMR,
    CAN,
    CYM,
    CAF,
    TCD,
    CHL,
    CHN,
    COL,
    COM,
    COG,
    COD,
    COK,
    CRI,
    CIV,
    HRV,
    CUB,
    CUW,
    CYP,
    CZE,
    DNK,
    DJI,
    DMA,
    DOM,
    ECU,
    EGY,
    SLV,
    GNQ,
    ERI,
    EST,
    SWZ,
    ETH,
    FLK,
    FRO,
    FJI,
    FIN,
    FRA,
    PYF,
    GAB,
    GMB,
    GEO,
    DEU,
    GHA,
    GIB,
    GRC,
    GRL,
    GRD,
    GUM,
    GTM,
    GGY,
    GIN,
    GNB,
    GUY,
    HTI,
    HND,
    HKG,
    HUN,
    ISL,
    IND,
    IDN,
    IRN,
    IRQ,
    IRL,
    IMN,
    ISR,
    ITA,
    JAM,
    JPN,
    JEY,
    JOR,
    KAZ,
    KEN,
    KIR,
    PRK,
    KOR,
    KWT,
    KGZ,
    LAO,
    LVA,
    LBN,
    LSO,
    LBR,
    LBY,
    LIE,
    LTU,
    LUX,
    MAC,
    MDG,
    MWI,
    MYS,
    MDV,
    MLI,
    MLT,
    MHL,
    MRT,
    MUS,
    MEX,
    FSM,
    MDA,
    MCO,
    MNG,
    MNE,
    MSR,
    MAR,
    MOZ,
    MMR,
    NAM,
    NRU,
    NPL,
    NLD,
    NCL,
    NZL,
    NIC,
    NER,
    NGA,
    NIU,
    NFK,
    MKD,
    MNP,
    NOR,
    OMN,
    PAK,
    PLW,
    PSE,
    PAN,
    PNG,
    PRY,
    PER,
    PHL,
    PCN,
    POL,
    PRT,
    PRI,
    QAT,
    ROU,
    RUS,
    RWA,
    BLM,
    SHN,
    KNA,
    LCA,
    MAF,
    SPM,
    VCT,
    WSM,
    SMR,
    STP,
    SAU,
    SEN,
    SRB,
    SYC,
    SLE,
    SGP,
    SXM,
    SVK,
    SVN,
    SLB,
    SOM,
    ZAF,
    SGS,
    SSD,
    ESP,
    LKA,
    SDN,
    SUR,
    SWE,
    CHE,
    SYR,
    TWN,
    TJK,
    TZA,
    THA,
    TLS,
    TGO,
    TON,
    TTO,
    TUN,
    TUR,
    TKM,
    TCA,
    TUV,
    UGA,
    UKR,
    ARE,
    GBR,
    USA,
    URY,
    UZB,
    VUT,
    VAT,
    VEN,
    VNM,
    ESH,
    YEM,
    ZMB,
    ZWE,
}

impl TryFrom<String> for CountryCode {
    type Error = Box<dyn Error>;

    fn try_from(value: String) -> Result<Self, Self::Error> {
        CountryCode::try_from(value.as_str())
    }
}

impl TryFrom<&str> for CountryCode {
    type Error = Box<dyn Error>;

    fn try_from(value: &str) -> Result<Self, Self::Error> {
        use CountryCode::*;

        Ok(match value {
            "AFG" => AFG,
            "ALB" => ALB,
            "DZA" => DZA,
            "ASM" => ASM,
            "AND" => AND,
            "AGO" => AGO,
            "AIA" => AIA,
            "ATA" => ATA,
            "ATG" => ATG,
            "ARG" => ARG,
            "ARM" => ARM,
            "ABW" => ABW,
            "AUS" => AUS,
            "AUT" => AUT,
            "AZE" => AZE,
            "BHS" => BHS,
            "BHR" => BHR,
            "BGD" => BGD,
            "BRB" => BRB,
            "BLR" => BLR,
            "BEL" => BEL,
            "BLZ" => BLZ,
            "BEN" => BEN,
            "BMU" => BMU,
            "BTN" => BTN,
            "BOL" => BOL,
            "BIH" => BIH,
            "BWA" => BWA,
            "BRA" => BRA,
            "IOT" => IOT,
            "BRN" => BRN,
            "BGR" => BGR,
            "BFA" => BFA,
            "BDI" => BDI,
            "CPV" => CPV,
            "KHM" => KHM,
            "CMR" => CMR,
            "CAN" => CAN,
            "CYM" => CYM,
            "CAF" => CAF,
            "TCD" => TCD,
            "CHL" => CHL,
            "CHN" => CHN,
            "COL" => COL,
            "COM" => COM,
            "COG" => COG,
            "COD" => COD,
            "COK" => COK,
            "CRI" => CRI,
            "CIV" => CIV,
            "HRV" => HRV,
            "CUB" => CUB,
            "CUW" => CUW,
            "CYP" => CYP,
            "CZE" => CZE,
            "DNK" => DNK,
            "DJI" => DJI,
            "DMA" => DMA,
            "DOM" => DOM,
            "ECU" => ECU,
            "EGY" => EGY,
            "SLV" => SLV,
            "GNQ" => GNQ,
            "ERI" => ERI,
            "EST" => EST,
            "SWZ" => SWZ,
            "ETH" => ETH,
            "FLK" => FLK,
            "FRO" => FRO,
            "FJI" => FJI,
            "FIN" => FIN,
            "FRA" => FRA,
            "PYF" => PYF,
            "GAB" => GAB,
            "GMB" => GMB,
            "GEO" => GEO,
            "DEU" => DEU,
            "GHA" => GHA,
            "GIB" => GIB,
            "GRC" => GRC,
            "GRL" => GRL,
            "GRD" => GRD,
            "GUM" => GUM,
            "GTM" => GTM,
            "GGY" => GGY,
            "GIN" => GIN,
            "GNB" => GNB,
            "GUY" => GUY,
            "HTI" => HTI,
            "HND" => HND,
            "HKG" => HKG,
            "HUN" => HUN,
            "ISL" => ISL,
            "IND" => IND,
            "IDN" => IDN,
            "IRN" => IRN,
            "IRQ" => IRQ,
            "IRL" => IRL,
            "IMN" => IMN,
            "ISR" => ISR,
            "ITA" => ITA,
            "JAM" => JAM,
            "JPN" => JPN,
            "JEY" => JEY,
            "JOR" => JOR,
            "KAZ" => KAZ,
            "KEN" => KEN,
            "KIR" => KIR,
            "PRK" => PRK,
            "KOR" => KOR,
            "KWT" => KWT,
            "KGZ" => KGZ,
            "LAO" => LAO,
            "LVA" => LVA,
            "LBN" => LBN,
            "LSO" => LSO,
            "LBR" => LBR,
            "LBY" => LBY,
            "LIE" => LIE,
            "LTU" => LTU,
            "LUX" => LUX,
            "MAC" => MAC,
            "MDG" => MDG,
            "MWI" => MWI,
            "MYS" => MYS,
            "MDV" => MDV,
            "MLI" => MLI,
            "MLT" => MLT,
            "MHL" => MHL,
            "MRT" => MRT,
            "MUS" => MUS,
            "MEX" => MEX,
            "FSM" => FSM,
            "MDA" => MDA,
            "MCO" => MCO,
            "MNG" => MNG,
            "MNE" => MNE,
            "MSR" => MSR,
            "MAR" => MAR,
            "MOZ" => MOZ,
            "MMR" => MMR,
            "NAM" => NAM,
            "NRU" => NRU,
            "NPL" => NPL,
            "NLD" => NLD,
            "NCL" => NCL,
            "NZL" => NZL,
            "NIC" => NIC,
            "NER" => NER,
            "NGA" => NGA,
            "NIU" => NIU,
            "NFK" => NFK,
            "MKD" => MKD,
            "MNP" => MNP,
            "NOR" => NOR,
            "OMN" => OMN,
            "PAK" => PAK,
            "PLW" => PLW,
            "PSE" => PSE,
            "PAN" => PAN,
            "PNG" => PNG,
            "PRY" => PRY,
            "PER" => PER,
            "PHL" => PHL,
            "PCN" => PCN,
            "POL" => POL,
            "PRT" => PRT,
            "PRI" => PRI,
            "QAT" => QAT,
            "ROU" => ROU,
            "RUS" => RUS,
            "RWA" => RWA,
            "BLM" => BLM,
            "SHN" => SHN,
            "KNA" => KNA,
            "LCA" => LCA,
            "MAF" => MAF,
            "SPM" => SPM,
            "VCT" => VCT,
            "WSM" => WSM,
            "SMR" => SMR,
            "STP" => STP,
            "SAU" => SAU,
            "SEN" => SEN,
            "SRB" => SRB,
            "SYC" => SYC,
            "SLE" => SLE,
            "SGP" => SGP,
            "SXM" => SXM,
            "SVK" => SVK,
            "SVN" => SVN,
            "SLB" => SLB,
            "SOM" => SOM,
            "ZAF" => ZAF,
            "SGS" => SGS,
            "SSD" => SSD,
            "ESP" => ESP,
            "LKA" => LKA,
            "SDN" => SDN,
            "SUR" => SUR,
            "SWE" => SWE,
            "CHE" => CHE,
            "SYR" => SYR,
            "TWN" => TWN,
            "TJK" => TJK,
            "TZA" => TZA,
            "THA" => THA,
            "TLS" => TLS,
            "TGO" => TGO,
            "TON" => TON,
            "TTO" => TTO,
            "TUN" => TUN,
            "TUR" => TUR,
            "TKM" => TKM,
            "TCA" => TCA,
            "TUV" => TUV,
            "UGA" => UGA,
            "UKR" => UKR,
            "ARE" => ARE,
            "GBR" => GBR,
            "USA" => USA,
            "URY" => URY,
            "UZB" => UZB,
            "VUT" => VUT,
            "VAT" => VAT,
            "VEN" => VEN,
            "VNM" => VNM,
            "ESH" => ESH,
            "YEM" => YEM,
            "ZMB" => ZMB,
            "ZWE" => ZWE,
            _ => return Err(format!("Unknown country code: {}", value).into()),
        })
    }
}

impl CountryCode {
    pub fn country_name(&self) -> &'static str {
        use CountryCode::*;

        match self {
            AFG => "Afghanistan ",
            ALB => "Albania",
            DZA => "Algeria",
            ASM => "American Samoa",
            AND => "Andorra",
            AGO => "Angola",
            AIA => "Anguilla",
            ATA => "Antarctica",
            ATG => "Antigua and Barbuda",
            ARG => "Argentina",
            ARM => "Armenia",
            ABW => "Aruba",
            AUS => "Australia",
            AUT => "Austria",
            AZE => "Azerbaijan",
            BHS => "Bahamas",
            BHR => "Bahrain",
            BGD => "Bangladesh",
            BRB => "Barbados",
            BLR => "Belarus",
            BEL => "Belgium",
            BLZ => "Belize",
            BEN => "Benin",
            BMU => "Bermuda",
            BTN => "Bhutan",
            BOL => "Bolivia",
            BIH => "Bosnia and Herzegovina",
            BWA => "Botswana",
            BRA => "Brazil",
            IOT => "British Indian Ocean Territory",
            BRN => "Brunei Darussalam",
            BGR => "Bulgaria",
            BFA => "Burkina Faso",
            BDI => "Burundi",
            CPV => "Cabo Verde",
            KHM => "Cambodia",
            CMR => "Cameroon",
            CAN => "Canada",
            CYM => "Cayman Islands",
            CAF => "Central African Republic",
            TCD => "Chad",
            CHL => "Chile",
            CHN => "China",
            COL => "Colombia",
            COM => "Comoros",
            COG => "Congo",
            COD => "Congo, Democratic Republic of the",
            COK => "Cook Islands",
            CRI => "Costa Rica",
            CIV => "Côte d'Ivoire",
            HRV => "Croatia",
            CUB => "Cuba",
            CUW => "Curaçao",
            CYP => "Cyprus",
            CZE => "Czechia",
            DNK => "Denmark",
            DJI => "Djibouti",
            DMA => "Dominica",
            DOM => "Dominican Republic",
            ECU => "Ecuador",
            EGY => "Egypt",
            SLV => "El Salvador",
            GNQ => "Equatorial Guinea",
            ERI => "Eritrea",
            EST => "Estonia",
            SWZ => "Eswatini",
            ETH => "Ethiopia",
            FLK => "Falkland Islands",
            FRO => "Faroe Islands",
            FJI => "Fiji",
            FIN => "Finland",
            FRA => "France",
            PYF => "French Polynesia",
            GAB => "Gabon",
            GMB => "Gambia",
            GEO => "Georgia",
            DEU => "Germany",
            GHA => "Ghana",
            GIB => "Gibraltar",
            GRC => "Greece",
            GRL => "Greenland",
            GRD => "Grenada",
            GUM => "Guam",
            GTM => "Guatemala",
            GGY => "Guernsey",
            GIN => "Guinea",
            GNB => "Guinea-Bissau",
            GUY => "Guyana",
            HTI => "Haiti",
            HND => "Honduras",
            HKG => "Hong Kong",
            HUN => "Hungary",
            ISL => "Iceland",
            IND => "India",
            IDN => "Indonesia",
            IRN => "Iran",
            IRQ => "Iraq",
            IRL => "Ireland",
            IMN => "Isle of Man",
            ISR => "Israel",
            ITA => "Italy",
            JAM => "Jamaica",
            JPN => "Japan",
            JEY => "Jersey",
            JOR => "Jordan",
            KAZ => "Kazakhstan",
            KEN => "Kenya",
            KIR => "Kiribati",
            PRK => "Korea, Democratic People's Republic of",
            KOR => "Korea, Republic of",
            KWT => "Kuwait",
            KGZ => "Kyrgyzstan",
            LAO => "Lao People's Democratic Republic",
            LVA => "Latvia",
            LBN => "Lebanon",
            LSO => "Lesotho",
            LBR => "Liberia",
            LBY => "Libya",
            LIE => "Liechtenstein",
            LTU => "Lithuania",
            LUX => "Luxembourg",
            MAC => "Macao",
            MDG => "Madagascar",
            MWI => "Malawi",
            MYS => "Malaysia",
            MDV => "Maldives",
            MLI => "Mali",
            MLT => "Malta",
            MHL => "Marshall Islands",
            MRT => "Mauritania",
            MUS => "Mauritius",
            MEX => "Mexico",
            FSM => "Micronesia",
            MDA => "Moldova",
            MCO => "Monaco",
            MNG => "Mongolia",
            MNE => "Montenegro",
            MSR => "Montserrat",
            MAR => "Morocco",
            MOZ => "Mozambique",
            MMR => "Myanmar",
            NAM => "Namibia",
            NRU => "Nauru",
            NPL => "Nepal",
            NLD => "Netherlands",
            NCL => "New Caledonia",
            NZL => "New Zealand",
            NIC => "Nicaragua",
            NER => "Niger",
            NGA => "Nigeria",
            NIU => "Niue",
            NFK => "Norfolk Island",
            MKD => "North Macedonia",
            MNP => "Northern Mariana Islands",
            NOR => "Norway",
            OMN => "Oman",
            PAK => "Pakistan",
            PLW => "Palau",
            PSE => "Palestine, State of",
            PAN => "Panama",
            PNG => "Papua New Guinea",
            PRY => "Paraguay",
            PER => "Peru",
            PHL => "Philippines",
            PCN => "Pitcairn",
            POL => "Poland",
            PRT => "Portugal",
            PRI => "Puerto Rico",
            QAT => "Qatar",
            ROU => "Romania",
            RUS => "Russian Federation",
            RWA => "Rwanda",
            BLM => "Saint Barthélemy",
            SHN => "Saint Helena, Ascension and Tristan da Cunha",
            KNA => "Saint Kitts and Nevis",
            LCA => "Saint Lucia",
            MAF => "Saint Martin",
            SPM => "Saint Pierre and Miquelon",
            VCT => "Saint Vincent and the Grenadines",
            WSM => "Samoa",
            SMR => "San Marino",
            STP => "Sao Tome and Principe",
            SAU => "Saudi Arabia",
            SEN => "Senegal",
            SRB => "Serbia",
            SYC => "Seychelles",
            SLE => "Sierra Leone",
            SGP => "Singapore",
            SXM => "Sint Maarten (Dutch part)",
            SVK => "Slovakia",
            SVN => "Slovenia",
            SLB => "Solomon Islands",
            SOM => "Somalia",
            ZAF => "South Africa",
            SGS => "South Georgia and the South Sandwich Islands",
            SSD => "South Sudan",
            ESP => "Spain",
            LKA => "Sri Lanka",
            SDN => "Sudan",
            SUR => "Suriname",
            SWE => "Sweden",
            CHE => "Switzerland",
            SYR => "Syrian Arab Republic",
            TWN => "Taiwan",
            TJK => "Tajikistan",
            TZA => "Tanzania, United Republic of",
            THA => "Thailand",
            TLS => "Timor-Leste",
            TGO => "Togo",
            TON => "Tonga",
            TTO => "Trinidad and Tobago",
            TUN => "Tunisia",
            TUR => "Turkey",
            TKM => "Turkmenistan",
            TCA => "Turks and Caicos Islands",
            TUV => "Tuvalu",
            UGA => "Uganda",
            UKR => "Ukraine",
            ARE => "United Arab Emirates",
            GBR => "United Kingdom of Great Britain and Northern Ireland",
            USA => "United States of America",
            URY => "Uruguay",
            UZB => "Uzbekistan",
            VUT => "Vanuatu",
            VEN => "Venezuela (Bolivarian Republic of)",
            VNM => "Viet Nam",
            ESH => "Western Sahara",
            YEM => "Yemen",
            ZMB => "Zambia",
            ZWE => "Zimbabwe",
            VAT => "Holy See (Vatican City State)",
        }
    }

    pub fn capital_coords(&self) -> Option<(f64, f64)> {
        match self {
            CountryCode::AFG => Some((69.1761, 34.5228)),
            CountryCode::ALB => Some((19.8172, 41.3317)),
            CountryCode::DZA => Some((3.0548, 36.7397)),
            CountryCode::ASM => Some((-170.691, -14.2846)),
            CountryCode::AND => Some((1.5218, 42.5075)),
            CountryCode::AGO => Some((13.242, -8.81155)),
            CountryCode::AIA => Some((-63.0686, 18.2206)),
            CountryCode::ATA => None,
            CountryCode::ATG => Some((-61.8456, 17.1175)),
            CountryCode::ARG => Some((-58.4173, -34.6118)),
            CountryCode::ARM => Some((44.509, 40.1596)),
            CountryCode::ABW => Some((-70.0311, 12.5246)),
            CountryCode::AUS => Some((149.124, -35.3075)),
            CountryCode::AUT => Some((16.3738, 48.2092)),
            CountryCode::AZE => Some((49.8932, 40.3834)),
            CountryCode::BHS => Some((-77.339, 25.0343)),
            CountryCode::BHR => Some((50.5354, 26.1921)),
            CountryCode::BGD => Some((90.4113, 23.7055)),
            CountryCode::BRB => Some((-59.6112, 13.0935)),
            CountryCode::BLR => Some((27.5766, 53.9678)),
            CountryCode::BEL => Some((4.36761, 50.8371)),
            CountryCode::BLZ => Some((-88.7601, 17.1899)),
            CountryCode::BEN => Some((2.6323, 6.4779)),
            CountryCode::BMU => Some((-64.7546, 32.313)),
            CountryCode::BTN => Some((89.633, 27.5142)),
            CountryCode::BOL => Some((-68.1193, -16.5004)),
            CountryCode::BIH => Some((18.4214, 43.8607)),
            CountryCode::BWA => Some((25.9201, -24.6544)),
            CountryCode::BRA => Some((-47.9292, -15.7801)),
            CountryCode::IOT => Some((71.2761, -6.3432)),
            CountryCode::BRN => Some((114.946, 4.5353)),
            CountryCode::BGR => Some((23.3238, 42.7105)),
            CountryCode::BFA => Some((-1.5616, 12.2383)),
            CountryCode::BDI => Some((29.3639, -3.3784)),
            CountryCode::CPV => Some((-23.9599, 15.9551)),
            CountryCode::KHM => Some((104.886, 12.5657)),
            CountryCode::CMR => Some((11.5174, 3.848)),
            CountryCode::CAN => Some((-75.6981, 45.4215)),
            CountryCode::CYM => Some((-81.2546, 19.3133)),
            CountryCode::CAF => Some((18.5826, 4.3947)),
            CountryCode::TCD => Some((15.0445, 12.1348)),
            CountryCode::CHL => Some((-70.6483, -33.4376)),
            CountryCode::CHN => Some((116.405, 39.9042)),
            CountryCode::COL => Some((-74.0721, 4.711)),
            CountryCode::COM => Some((43.8722, -11.875)),
            CountryCode::COG => Some((15.8277, -0.228)),
            CountryCode::COD => Some((15.8277, -4.0383)),
            CountryCode::COK => Some((-159.777, -21.2367)),
            CountryCode::CRI => Some((-84.0916, 9.7489)),
            CountryCode::CIV => Some((-4.0305, 5.3599)),
            CountryCode::HRV => Some((15.978, 45.815)),
            CountryCode::CUB => Some((-82.3666, 23.1136)),
            CountryCode::CUW => Some((-68.9721, 12.1696)),
            CountryCode::CYP => Some((33.4299, 35.1264)),
            CountryCode::CZE => Some((14.4205, 50.0878)),
            CountryCode::DNK => Some((12.5683, 55.6761)),
            CountryCode::DJI => Some((42.5903, 11.8251)),
            CountryCode::COL => Some((-74.0721, 4.711)),
            CountryCode::COM => Some((43.8722, -11.875)),
            CountryCode::COG => Some((15.8277, -0.228)),
            CountryCode::COD => Some((15.8277, -4.0383)),
            CountryCode::COK => Some((-159.777, -21.2367)),
            CountryCode::CRI => Some((-84.0916, 9.7489)),
            CountryCode::CIV => Some((-4.0305, 5.3599)),
            CountryCode::HRV => Some((15.978, 45.815)),
            CountryCode::CUB => Some((-82.3666, 23.1136)),
            CountryCode::CUW => Some((-68.9721, 12.1696)),
            CountryCode::CYP => Some((33.4299, 35.1264)),
            CountryCode::CZE => Some((14.4205, 50.0878)),
            CountryCode::DNK => Some((12.5683, 55.6761)),
            CountryCode::DJI => Some((42.5903, 11.8251)),
            CountryCode::DMA => Some((-61.3709, 15.3092)),
            CountryCode::DOM => Some((-69.9312, 18.4861)),
            CountryCode::ECU => Some((-78.4678, -0.1807)),
            CountryCode::EGY => Some((31.2357, 30.0444)),
            CountryCode::SLV => Some((-89.2073, 13.6929)),
            CountryCode::GNQ => Some((8.7832, 3.7507)),
            CountryCode::ERI => Some((38.9318, 15.3229)),
            CountryCode::EST => Some((24.7535, 59.437)),
            CountryCode::SWZ => Some((31.4659, -26.5225)),
            CountryCode::ETH => Some((38.7578, 9.03)),
            CountryCode::FLK => Some((-59.5236, -51.7963)),
            CountryCode::FRO => Some((-6.9118, 62.0079)),
            CountryCode::FJI => Some((178.4419, -18.1248)),
            CountryCode::FIN => Some((24.941, 60.1695)),
            CountryCode::FRA => Some((2.3522, 48.8566)),
            CountryCode::PYF => Some((-149.5665, -17.5516)),
            CountryCode::GAB => Some((9.451, 0.4162)),
            CountryCode::GMB => Some((-16.5917, 13.4549)),
            CountryCode::GEO => Some((44.793, 41.7151)),
            CountryCode::DEU => Some((13.405, 52.52)),
            CountryCode::GHA => Some((-0.186964, 5.6037)),
            CountryCode::GIB => Some((-5.3454, 36.1408)),
            CountryCode::GRC => Some((23.7275, 37.9838)),
            CountryCode::GRL => Some((-51.7216, 64.1835)),
            CountryCode::GRD => Some((-61.7486, 12.0561)),
            CountryCode::GUM => Some((144.7504, 13.4443)),
            CountryCode::GTM => Some((-90.5069, 14.6349)),
            CountryCode::GGY => Some((-2.5853, 49.455)),
            CountryCode::GIN => Some((-13.7006, 9.6412)),
            CountryCode::GNB => Some((-15.1804, 11.8817)),
            CountryCode::GUY => Some((-58.1551, 6.8013)),
            CountryCode::HTI => Some((-72.2852, 18.5944)),
            CountryCode::HND => Some((-87.2068, 14.0723)),
            CountryCode::HKG => Some((114.1694, 22.3193)),
            CountryCode::HUN => Some((19.0402, 47.4979)),
            CountryCode::ISL => Some((-21.8277, 64.1355)),
            CountryCode::IND => Some((77.209, 28.6139)),
            CountryCode::IDN => Some((106.8456, -6.2088)),
            CountryCode::IRN => Some((51.389, 35.6892)),
            CountryCode::IRQ => Some((44.3661, 33.3152)),
            CountryCode::IRL => Some((-6.2603, 53.3498)),
            CountryCode::IMN => Some((-4.4793, 54.2361)),
            CountryCode::ISR => Some((35.2137, 31.7683)),
            CountryCode::ITA => Some((12.4964, 41.9028)),
            CountryCode::JAM => Some((-76.792, 18.1096)),
            CountryCode::JPN => Some((139.6917, 35.6895)),
            CountryCode::JEY => Some((-2.1313, 49.2144)),
            CountryCode::JOR => Some((35.9306, 31.9454)),
            CountryCode::KAZ => Some((71.4278, 51.1694)),
            CountryCode::KEN => Some((36.8219, -1.2921)),
            CountryCode::KIR => Some((173.0006, 1.4518)),
            CountryCode::PRK => Some((125.7625, 39.0392)),
            CountryCode::KOR => Some((126.978, 37.5665)),
            CountryCode::KWT => Some((47.9774, 29.3759)),
            CountryCode::KGZ => Some((74.5698, 42.8746)),
            CountryCode::LAO => Some((102.6, 17.9667)),
            CountryCode::LVA => Some((24.1052, 56.9496)),
            CountryCode::LBN => Some((35.4955, 33.8938)),
            CountryCode::LSO => Some((27.4786, -29.3158)),
            CountryCode::LBR => Some((-10.7969, 6.3004)),
            CountryCode::LBY => Some((13.1913, 32.8872)),
            CountryCode::LIE => Some((9.5209, 47.141)),
            CountryCode::LTU => Some((25.2797, 54.6872)),
            CountryCode::LUX => Some((6.1319, 49.6117)),
            CountryCode::MAC => Some((113.5439, 22.1987)),
            CountryCode::MDG => Some((47.5162, -18.8792)),
            CountryCode::MWI => Some((33.7741, -13.9626)),
            CountryCode::MYS => Some((101.6869, 3.139)),
            CountryCode::MDV => Some((73.5093, 4.1755)),
            CountryCode::MLI => Some((-7.9922, 12.6392)),
            CountryCode::MLT => Some((14.5146, 35.8989)),
            CountryCode::MHL => Some((171.384, 7.1164)),
            CountryCode::PSE => Some((35.2041, 31.9522)),
            CountryCode::MRT => Some((-15.965, 18.0735)),
            CountryCode::MUS => Some((57.5522, -20.1609)),
            CountryCode::MEX => Some((-99.1332, 19.4326)),
            CountryCode::FSM => Some((158.215, 6.9248)),
            CountryCode::MDA => Some((28.8638, 47.0105)),
            CountryCode::MCO => Some((7.4246, 43.7384)),
            CountryCode::MNG => Some((106.9057, 47.8864)),
            CountryCode::MNE => Some((19.2595, 42.441)),
            CountryCode::MSR => Some((-62.1874, 16.7425)),
            CountryCode::MAR => Some((-6.8498, 34.0209)),
            CountryCode::MOZ => Some((32.5887, -25.9537)),
            CountryCode::MMR => Some((96.1951, 16.8409)),
            CountryCode::NAM => Some((17.0832, -22.5595)),
            CountryCode::NRU => Some((166.9315, -0.5228)),
            CountryCode::NPL => Some((85.324, 27.7172)),
            CountryCode::NLD => Some((4.9041, 52.3676)),
            CountryCode::NCL => Some((166.4505, -22.2558)),
            CountryCode::NZL => Some((174.7762, -41.2865)),
            CountryCode::NIC => Some((-86.2514, 12.1364)),
            CountryCode::NER => Some((2.1098, 13.5127)),
            CountryCode::NGA => Some((7.4893, 9.0579)),
            CountryCode::NIU => Some((-169.8672, -19.0544)),
            CountryCode::NFK => Some((167.9547, -29.0408)),
            CountryCode::MKD => Some((21.4316, 41.9981)),
            CountryCode::MNP => Some((145.7064, 15.2123)),
            CountryCode::NOR => Some((10.7522, 59.9139)),
            CountryCode::OMN => Some((58.5933, 23.5859)),
            CountryCode::PAK => Some((73.0479, 33.6844)),
            CountryCode::PLW => Some((134.479, 7.5149)),
            CountryCode::PAN => Some((-79.5199, 8.9824)),
            CountryCode::PNG => Some((147.1797, -9.478)),
            CountryCode::PRY => Some((-57.5759, -25.2637)),
            CountryCode::PER => Some((-77.0428, -12.0464)),
            CountryCode::PHL => Some((120.9842, 14.5995)),
            CountryCode::PCN => Some((-130.1005, -25.066)),
            CountryCode::POL => Some((21.0122, 52.2297)),
            CountryCode::PRT => Some((-9.139, 38.7167)),
            CountryCode::PRI => Some((-66.1057, 18.4655)),
            CountryCode::QAT => Some((51.520008, 25.276987)),
            CountryCode::ROU => Some((26.1025, 44.4268)),
            CountryCode::RUS => Some((37.6173, 55.7558)),
            CountryCode::RWA => Some((30.0619, -1.9441)),
            CountryCode::BLM => Some((-62.8508, 17.8962)),
            CountryCode::SHN => Some((-5.7089, -15.965)),
            CountryCode::KNA => Some((-62.783, 17.3578)),
            CountryCode::LCA => Some((-60.9875, 14.0101)),
            CountryCode::MAF => Some((-63.0501, 18.0708)),
            CountryCode::SPM => Some((-56.1773, 46.7758)),
            CountryCode::VCT => Some((-61.2013, 13.2528)),
            CountryCode::WSM => Some((-171.7658, -13.759)),
            CountryCode::SMR => Some((12.4578, 43.9424)),
            CountryCode::STP => Some((6.6131, 0.1864)),
            CountryCode::SAU => Some((46.6753, 24.7136)),
            CountryCode::SEN => Some((-17.4439, 14.7167)),
            CountryCode::SRB => Some((20.4489, 44.7866)),
            CountryCode::SYC => Some((55.4513, -4.6796)),
            CountryCode::SLE => Some((-13.2344, 8.484)),
            CountryCode::SGP => Some((103.8198, 1.3521)),
            CountryCode::SXM => Some((-63.0571, 18.0425)),
            CountryCode::SVK => Some((17.1073, 48.1486)),
            CountryCode::SVN => Some((14.9955, 46.0569)),
            CountryCode::SLB => Some((159.5925, -9.6457)),
            CountryCode::SOM => Some((45.3438, 2.0469)),
            CountryCode::ZAF => Some((28.0473, -26.2041)),
            CountryCode::SGS => Some((-36.4332, -54.4296)),
            CountryCode::SSD => Some((31.306, 6.8769)),
            CountryCode::ESP => Some((-3.7038, 40.4168)),
            CountryCode::LKA => Some((79.8612, 7.8731)),
            CountryCode::SDN => Some((32.5599, 15.5007)),
            CountryCode::SUR => Some((-55.2038, 5.852)),
            CountryCode::SWE => Some((18.0686, 59.3293)),
            CountryCode::CHE => Some((7.4474, 46.948)),
            CountryCode::SYR => Some((36.2021, 33.5138)),
            CountryCode::TWN => Some((121.5654, 25.0329)),
            CountryCode::TJK => Some((68.7739, 38.861)),
            CountryCode::TZA => Some((35.7372, -6.163)),
            CountryCode::THA => Some((100.5018, 13.7563)),
            CountryCode::TLS => Some((125.7275, -8.8742)),
            CountryCode::TGO => Some((1.2195, 6.5244)),
            CountryCode::TON => Some((-175.1982, -21.1789)),
            CountryCode::TTO => Some((-61.2225, 10.6918)),
            CountryCode::TUN => Some((10.1815, 36.8065)),
            CountryCode::TUR => Some((28.9784, 41.0082)),
            CountryCode::TKM => Some((58.3838, 38.9697)),
            CountryCode::TCA => Some((-71.7979, 21.694)),
            CountryCode::TUV => Some((179.1946, -7.1095)),
            CountryCode::UGA => Some((32.2903, 0.3136)),
            CountryCode::UKR => Some((30.5234, 50.4501)),
            CountryCode::ARE => Some((54.3705, 24.4764)),
            CountryCode::GBR => Some((-0.1276, 51.5074)),
            CountryCode::USA => Some((-77.0369, 38.9072)),
            CountryCode::URY => Some((-56.1645, -34.9011)),
            CountryCode::UZB => Some((69.2401, 41.3775)),
            CountryCode::VUT => Some((168.3219, -17.7328)),
            CountryCode::VEN => Some((-66.9036, 10.4806)),
            CountryCode::VNM => Some((105.8544, 21.0285)),
            CountryCode::ESH => Some((-13.1956, 24.2155)),
            CountryCode::YEM => Some((44.2088, 15.5527)),
            CountryCode::ZMB => Some((28.2937, -15.3982)),
            CountryCode::ZWE => Some((31.0456, -17.8252)),
            CountryCode::VAT => Some((12.4534, 41.9029)),
        }
    }
}

impl std::fmt::Display for CountryCode {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(
            f,
            "{}",
            match self {
                CountryCode::AFG => "AFG",
                CountryCode::ALB => "ALB",
                CountryCode::DZA => "DZA",
                CountryCode::ASM => "ASM",
                CountryCode::AND => "AND",
                CountryCode::AGO => "AGO",
                CountryCode::AIA => "AIA",
                CountryCode::ATA => "ATA",
                CountryCode::ATG => "ATG",
                CountryCode::ARG => "ARG",
                CountryCode::ARM => "ARM",
                CountryCode::ABW => "ABW",
                CountryCode::AUS => "AUS",
                CountryCode::AUT => "AUT",
                CountryCode::AZE => "AZE",
                CountryCode::BHS => "BHS",
                CountryCode::BHR => "BHR",
                CountryCode::BGD => "BGD",
                CountryCode::BRB => "BRB",
                CountryCode::BLR => "BLR",
                CountryCode::BEL => "BEL",
                CountryCode::BLZ => "BLZ",
                CountryCode::BEN => "BEN",
                CountryCode::BMU => "BMU",
                CountryCode::BTN => "BTN",
                CountryCode::BOL => "BOL",
                CountryCode::BIH => "BIH",
                CountryCode::BWA => "BWA",
                CountryCode::BRA => "BRA",
                CountryCode::IOT => "IOT",
                CountryCode::BRN => "BRN",
                CountryCode::BGR => "BGR",
                CountryCode::BFA => "BFA",
                CountryCode::BDI => "BDI",
                CountryCode::CPV => "CPV",
                CountryCode::KHM => "KHM",
                CountryCode::CMR => "CMR",
                CountryCode::CAN => "CAN",
                CountryCode::CYM => "CYM",
                CountryCode::CAF => "CAF",
                CountryCode::TCD => "TCD",
                CountryCode::CHL => "CHL",
                CountryCode::CHN => "CHN",
                CountryCode::COL => "COL",
                CountryCode::COM => "COM",
                CountryCode::COG => "COG",
                CountryCode::COD => "COD",
                CountryCode::COK => "COK",
                CountryCode::CRI => "CRI",
                CountryCode::CIV => "CIV",
                CountryCode::HRV => "HRV",
                CountryCode::CUB => "CUB",
                CountryCode::CUW => "CUW",
                CountryCode::CYP => "CYP",
                CountryCode::CZE => "CZE",
                CountryCode::DNK => "DNK",
                CountryCode::DJI => "DJI",
                CountryCode::DMA => "DMA",
                CountryCode::DOM => "DOM",
                CountryCode::ECU => "ECU",
                CountryCode::EGY => "EGY",
                CountryCode::SLV => "SLV",
                CountryCode::GNQ => "GNQ",
                CountryCode::ERI => "ERI",
                CountryCode::EST => "EST",
                CountryCode::SWZ => "SWZ",
                CountryCode::ETH => "ETH",
                CountryCode::FLK => "FLK",
                CountryCode::FRO => "FRO",
                CountryCode::FJI => "FJI",
                CountryCode::FIN => "FIN",
                CountryCode::FRA => "FRA",
                CountryCode::PYF => "PYF",
                CountryCode::GAB => "GAB",
                CountryCode::GMB => "GMB",
                CountryCode::GEO => "GEO",
                CountryCode::DEU => "DEU",
                CountryCode::GHA => "GHA",
                CountryCode::GIB => "GIB",
                CountryCode::GRC => "GRC",
                CountryCode::GRL => "GRL",
                CountryCode::GRD => "GRD",
                CountryCode::GUM => "GUM",
                CountryCode::GTM => "GTM",
                CountryCode::GGY => "GGY",
                CountryCode::GIN => "GIN",
                CountryCode::GNB => "GNB",
                CountryCode::GUY => "GUY",
                CountryCode::HTI => "HTI",
                CountryCode::HND => "HND",
                CountryCode::HKG => "HKG",
                CountryCode::HUN => "HUN",
                CountryCode::ISL => "ISL",
                CountryCode::IND => "IND",
                CountryCode::IDN => "IDN",
                CountryCode::IRN => "IRN",
                CountryCode::IRQ => "IRQ",
                CountryCode::IRL => "IRL",
                CountryCode::IMN => "IMN",
                CountryCode::ISR => "ISR",
                CountryCode::ITA => "ITA",
                CountryCode::JAM => "JAM",
                CountryCode::JPN => "JPN",
                CountryCode::JEY => "JEY",
                CountryCode::JOR => "JOR",
                CountryCode::KAZ => "KAZ",
                CountryCode::KEN => "KEN",
                CountryCode::KIR => "KIR",
                CountryCode::PRK => "PRK",
                CountryCode::KOR => "KOR",
                CountryCode::KWT => "KWT",
                CountryCode::KGZ => "KGZ",
                CountryCode::LAO => "LAO",
                CountryCode::LVA => "LVA",
                CountryCode::LBN => "LBN",
                CountryCode::LSO => "LSO",
                CountryCode::LBR => "LBR",
                CountryCode::LBY => "LBY",
                CountryCode::LIE => "LIE",
                CountryCode::LTU => "LTU",
                CountryCode::LUX => "LUX",
                CountryCode::MAC => "MAC",
                CountryCode::MDG => "MDG",
                CountryCode::MWI => "MWI",
                CountryCode::MYS => "MYS",
                CountryCode::MDV => "MDV",
                CountryCode::MLI => "MLI",
                CountryCode::MLT => "MLT",
                CountryCode::MHL => "MHL",
                CountryCode::MRT => "MRT",
                CountryCode::MUS => "MUS",
                CountryCode::MEX => "MEX",
                CountryCode::FSM => "FSM",
                CountryCode::MDA => "MDA",
                CountryCode::MCO => "MCO",
                CountryCode::MNG => "MNG",
                CountryCode::MNE => "MNE",
                CountryCode::MSR => "MSR",
                CountryCode::MAR => "MAR",
                CountryCode::MOZ => "MOZ",
                CountryCode::MMR => "MMR",
                CountryCode::NAM => "NAM",
                CountryCode::NRU => "NRU",
                CountryCode::NPL => "NPL",
                CountryCode::NLD => "NLD",
                CountryCode::NCL => "NCL",
                CountryCode::NZL => "NZL",
                CountryCode::NIC => "NIC",
                CountryCode::NER => "NER",
                CountryCode::NGA => "NGA",
                CountryCode::NIU => "NIU",
                CountryCode::NFK => "NFK",
                CountryCode::MKD => "MKD",
                CountryCode::MNP => "MNP",
                CountryCode::NOR => "NOR",
                CountryCode::OMN => "OMN",
                CountryCode::PAK => "PAK",
                CountryCode::PLW => "PLW",
                CountryCode::PSE => "PSE",
                CountryCode::PAN => "PAN",
                CountryCode::PNG => "PNG",
                CountryCode::PRY => "PRY",
                CountryCode::PER => "PER",
                CountryCode::PHL => "PHL",
                CountryCode::PCN => "PCN",
                CountryCode::POL => "POL",
                CountryCode::PRT => "PRT",
                CountryCode::PRI => "PRI",
                CountryCode::QAT => "QAT",
                CountryCode::ROU => "ROU",
                CountryCode::RUS => "RUS",
                CountryCode::RWA => "RWA",
                CountryCode::BLM => "BLM",
                CountryCode::SHN => "SHN",
                CountryCode::KNA => "KNA",
                CountryCode::LCA => "LCA",
                CountryCode::MAF => "MAF",
                CountryCode::SPM => "SPM",
                CountryCode::VCT => "VCT",
                CountryCode::WSM => "WSM",
                CountryCode::SMR => "SMR",
                CountryCode::STP => "STP",
                CountryCode::SAU => "SAU",
                CountryCode::SEN => "SEN",
                CountryCode::SRB => "SRB",
                CountryCode::SYC => "SYC",
                CountryCode::SLE => "SLE",
                CountryCode::SGP => "SGP",
                CountryCode::SXM => "SXM",
                CountryCode::SVK => "SVK",
                CountryCode::SVN => "SVN",
                CountryCode::SLB => "SLB",
                CountryCode::SOM => "SOM",
                CountryCode::ZAF => "ZAF",
                CountryCode::SGS => "SGS",
                CountryCode::SSD => "SSD",
                CountryCode::ESP => "ESP",
                CountryCode::LKA => "LKA",
                CountryCode::SDN => "SDN",
                CountryCode::SUR => "SUR",
                CountryCode::SWE => "SWE",
                CountryCode::CHE => "CHE",
                CountryCode::SYR => "SYR",
                CountryCode::TWN => "TWN",
                CountryCode::TJK => "TJK",
                CountryCode::TZA => "TZA",
                CountryCode::THA => "THA",
                CountryCode::TLS => "TLS",
                CountryCode::TGO => "TGO",
                CountryCode::TON => "TON",
                CountryCode::TTO => "TTO",
                CountryCode::TUN => "TUN",
                CountryCode::TUR => "TUR",
                CountryCode::TKM => "TKM",
                CountryCode::TCA => "TCA",
                CountryCode::TUV => "TUV",
                CountryCode::UGA => "UGA",
                CountryCode::UKR => "UKR",
                CountryCode::ARE => "ARE",
                CountryCode::GBR => "GBR",
                CountryCode::USA => "USA",
                CountryCode::URY => "URY",
                CountryCode::UZB => "UZB",
                CountryCode::VUT => "VUT",
                CountryCode::VAT => "VAT",
                CountryCode::VEN => "VEN",
                CountryCode::VNM => "VNM",
                CountryCode::ESH => "ESH",
                CountryCode::YEM => "YEM",
                CountryCode::ZMB => "ZMB",
                CountryCode::ZWE => "ZWE",
            }
        )
    }
}
